name: Start Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install jq
      run: sudo apt-get install jq
    
     - name: Load data
      run: |
        curl -X 'POST' \
        "https://${{ secrets.ENV_HOST }}:8443/qs/systems/local/queries" \
        -H "Authorization: Basic ${{ secrets.ENV_AUTH }}" \
        -H "Accept: application/vnd.com.teradata.rest-v1.0+json" \
        -H "Content-Type: application/json" \
        -d '{
               "query": "INSERT INTO teddy_retailers_ci.new_online_store (transaction_id, name_customer, surname, email, order_status, name_product, price_cents) VALUES (1, "John", "Doe", "john.doe@example.com", "Shipped", "Laptop", 120000);",
              "format": "array",
              "includeColumns": true
            }'
    
    - name: Send Query and Check Result
      run: |
        result=$(curl -X 'POST' \
          "https://${{ secrets.ENV_HOST}}:8443/qs/systems/local/queries" \
          -H "Authorization: Basic ${{ secrets.ENV_AUTH }}" \
          -H "Accept: application/vnd.com.teradata.rest-v1.0+json" \
          -H "Content-Type: application/json" \
          -d '{
                "query": "SELECT count(*) FROM teddy_retailers_ci.new_online_store WHERE transaction_id = 1;",
                "format": "array",
                "includeColumns": true
              }' \
          --insecure) 
          
        count=$(echo $result | jq -r '.results[0].data[0][0]')
        echo $count

        if [[ "$count" == "1" ]]; then
          echo "Test Passed"
        else
          echo "Test Failed"
          exit 1
        fi