name: Start Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install jq
      run: sudo apt-get install jq
    
    - name: Create DB
      run: |
        curl -X 'POST' \
        --insecure \
        -v \
        "https://cicdtest-wteuh1djm0q9u4x5.env.clearscape.teradata.com:8443/qs/systems/local/queries" \
        -H "Authorization: Basic ${{ secrets.ENV_AUTH }}" \
        -H "Accept: application/vnd.com.teradata.rest-v1.0+json" \
        -H "Content-Type: application/json" \
        -d '{
              "query": "CREATE DATABASE teddy_retailers_ci AS PERMANENT = 110e6;",
              "format": "array",
              "includeColumns": true
            }' 

  